server:
  context-path: /qbank
  port: 8081

# DataSource Jdbc Config
spring:
  datasource:
    url: jdbc:mysql://192.168.20.155:3306/authority?useUnicode=true&characterEncoding=gbk
    username: root
    password: root


# Druid Config
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
# Mybatis Config
#mybatis:
#  config-location: classpath:com/fitt/gbt/qbank/mapper/*Mapper.xml
#  type-aliases-package: com.fitt.gbt.qbank.domain

# Log config
logging:
  level:
    root: info
  file: ./logs/qbank.log


