server:
  port: 8877

# DataSource Jdbc Config
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/residence?useUnicode=true&characterEncoding=gbk
    username: root
    password: mysqlroot
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# JSON返回时间格式统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Mybatis-Plus Config
mybatis-plus:
  mapper-locations: classpath/mapper/*Mapper.xml

# Log config
logging:
  level:
    root: DEBUG
  file: ./logs/qbank.log

# Custom package Logging Level
logging.level.org.apache.ibatis: WARN
logging.level.org.mybatis.spring: WARN
logging.level.org.mybatis.spring.boot: WARN
logging.level.org.springframework.data: WARN
logging.level.org.springframework.web: WARN
logging.level.org.apache: WARN
logging.level.org.apache.tomcat: WARN
logging.level.org.apache.tomcat.util.net: WARN
